/* 
* Copyright (c) 2013, Nordic Semiconductor ASA
* All rights reserved.
* 
* Redistribution and use in source and binary forms, with or without modification,
* are permitted provided that the following conditions are met:
* 
* - Redistributions of source code must retain the above copyright notice, this
*   list of conditions and the following disclaimer.
* 
* - Redistributions in binary form must reproduce the above copyright notice, this
*   list of conditions and the following disclaimer in the documentation and/or
*   other materials provided with the distribution.
* 
* - The name of Nordic Semiconductor ASA may not be used to endorse or promote
*   products derived from this software without specific prior written permission.
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
* ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
* This file is autogenerated by nRFgo Studio 1.16.1.3119
*/

#include "services.h"
#include "lib_aci.h"

static bool is_gap_device_name_set_requested = false;
static bool is_brightness_brightness_send_requested = false;
static bool is_distance_distanceirfront_send_requested = false;
static bool is_distance_distanceirrear_send_requested = false;
static bool is_distance_distanceusfront_send_requested = false;
static bool is_distance_distanceusrear_send_requested = false;
static bool is_batterylevel_batterylevel_send_requested = false;
static bool is_generic_genericsensor1_send_requested = false;
static bool is_generic_genericsensor2_send_requested = false;

static void *gap_device_name_set;
static uint8_t gap_device_name_set_size;
static void *brightness_brightness_tx;
static uint8_t brightness_brightness_tx_size;
static void *distance_distanceirfront_tx;
static uint8_t distance_distanceirfront_tx_size;
static void *distance_distanceirrear_tx;
static uint8_t distance_distanceirrear_tx_size;
static void *distance_distanceusfront_tx;
static uint8_t distance_distanceusfront_tx_size;
static void *distance_distanceusrear_tx;
static uint8_t distance_distanceusrear_tx_size;
static void *batterylevel_batterylevel_tx;
static uint8_t batterylevel_batterylevel_tx_size;
static void *generic_genericsensor1_tx;
static uint8_t generic_genericsensor1_tx_size;
static void *generic_genericsensor2_tx;
static uint8_t generic_genericsensor2_tx_size;

static bool gap_device_name_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_GAP_DEVICE_NAME_SET, (void*)gap_device_name_set, gap_device_name_set_size));
}

void services_set_gap_device_name(void *src, int size)
{
  gap_device_name_set_size = size;
  gap_device_name_set = src;
  is_gap_device_name_set_requested = true;
  services_update_pipes();
}
static bool brightness_brightness_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_BRIGHTNESS_BRIGHTNESS_TX))
  {
    return(lib_aci_send_data(PIPE_BRIGHTNESS_BRIGHTNESS_TX, (void*)brightness_brightness_tx, brightness_brightness_tx_size));
  }
  return(false);
}

bool services_send_brightness_brightness(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_brightness_brightness_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_brightness_brightness_send_requested)
    {
      brightness_brightness_tx_size = size;
      brightness_brightness_tx = src;
      is_brightness_brightness_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    brightness_brightness_tx_size = size;
    brightness_brightness_tx = src;
    is_brightness_brightness_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool distance_distanceirfront_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_DISTANCE_DISTANCEIRFRONT_TX))
  {
    return(lib_aci_send_data(PIPE_DISTANCE_DISTANCEIRFRONT_TX, (void*)distance_distanceirfront_tx, distance_distanceirfront_tx_size));
  }
  return(false);
}

bool services_send_distance_distanceirfront(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_distance_distanceirfront_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_distance_distanceirfront_send_requested)
    {
      distance_distanceirfront_tx_size = size;
      distance_distanceirfront_tx = src;
      is_distance_distanceirfront_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    distance_distanceirfront_tx_size = size;
    distance_distanceirfront_tx = src;
    is_distance_distanceirfront_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool distance_distanceirrear_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_DISTANCE_DISTANCEIRREAR_TX))
  {
    return(lib_aci_send_data(PIPE_DISTANCE_DISTANCEIRREAR_TX, (void*)distance_distanceirrear_tx, distance_distanceirrear_tx_size));
  }
  return(false);
}

bool services_send_distance_distanceirrear(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_distance_distanceirrear_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_distance_distanceirrear_send_requested)
    {
      distance_distanceirrear_tx_size = size;
      distance_distanceirrear_tx = src;
      is_distance_distanceirrear_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    distance_distanceirrear_tx_size = size;
    distance_distanceirrear_tx = src;
    is_distance_distanceirrear_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool distance_distanceusfront_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_DISTANCE_DISTANCEUSFRONT_TX))
  {
    return(lib_aci_send_data(PIPE_DISTANCE_DISTANCEUSFRONT_TX, (void*)distance_distanceusfront_tx, distance_distanceusfront_tx_size));
  }
  return(false);
}

bool services_send_distance_distanceusfront(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_distance_distanceusfront_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_distance_distanceusfront_send_requested)
    {
      distance_distanceusfront_tx_size = size;
      distance_distanceusfront_tx = src;
      is_distance_distanceusfront_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    distance_distanceusfront_tx_size = size;
    distance_distanceusfront_tx = src;
    is_distance_distanceusfront_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool distance_distanceusrear_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_DISTANCE_DISTANCEUSREAR_TX))
  {
    return(lib_aci_send_data(PIPE_DISTANCE_DISTANCEUSREAR_TX, (void*)distance_distanceusrear_tx, distance_distanceusrear_tx_size));
  }
  return(false);
}

bool services_send_distance_distanceusrear(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_distance_distanceusrear_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_distance_distanceusrear_send_requested)
    {
      distance_distanceusrear_tx_size = size;
      distance_distanceusrear_tx = src;
      is_distance_distanceusrear_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    distance_distanceusrear_tx_size = size;
    distance_distanceusrear_tx = src;
    is_distance_distanceusrear_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool batterylevel_batterylevel_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_BATTERYLEVEL_BATTERYLEVEL_TX))
  {
    return(lib_aci_send_data(PIPE_BATTERYLEVEL_BATTERYLEVEL_TX, (void*)batterylevel_batterylevel_tx, batterylevel_batterylevel_tx_size));
  }
  return(false);
}

bool services_send_batterylevel_batterylevel(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_batterylevel_batterylevel_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_batterylevel_batterylevel_send_requested)
    {
      batterylevel_batterylevel_tx_size = size;
      batterylevel_batterylevel_tx = src;
      is_batterylevel_batterylevel_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    batterylevel_batterylevel_tx_size = size;
    batterylevel_batterylevel_tx = src;
    is_batterylevel_batterylevel_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool generic_genericsensor1_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_GENERIC_GENERICSENSOR1_TX))
  {
    return(lib_aci_send_data(PIPE_GENERIC_GENERICSENSOR1_TX, (void*)generic_genericsensor1_tx, generic_genericsensor1_tx_size));
  }
  return(false);
}

bool services_send_generic_genericsensor1(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_generic_genericsensor1_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_generic_genericsensor1_send_requested)
    {
      generic_genericsensor1_tx_size = size;
      generic_genericsensor1_tx = src;
      is_generic_genericsensor1_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    generic_genericsensor1_tx_size = size;
    generic_genericsensor1_tx = src;
    is_generic_genericsensor1_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool generic_genericsensor2_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_GENERIC_GENERICSENSOR2_TX))
  {
    return(lib_aci_send_data(PIPE_GENERIC_GENERICSENSOR2_TX, (void*)generic_genericsensor2_tx, generic_genericsensor2_tx_size));
  }
  return(false);
}

bool services_send_generic_genericsensor2(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_generic_genericsensor2_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_generic_genericsensor2_send_requested)
    {
      generic_genericsensor2_tx_size = size;
      generic_genericsensor2_tx = src;
      is_generic_genericsensor2_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    generic_genericsensor2_tx_size = size;
    generic_genericsensor2_tx = src;
    is_generic_genericsensor2_send_requested = true;
    services_update_pipes();
    return(true);
  }
}

void services_update_pipes(void)
{
  if(is_gap_device_name_set_requested)
  {
    is_gap_device_name_set_requested = !(gap_device_name_update_set());
  }
  if(is_brightness_brightness_send_requested)
  {
    is_brightness_brightness_send_requested = !(brightness_brightness_update_send());
  }
  if(is_distance_distanceirfront_send_requested)
  {
    is_distance_distanceirfront_send_requested = !(distance_distanceirfront_update_send());
  }
  if(is_distance_distanceirrear_send_requested)
  {
    is_distance_distanceirrear_send_requested = !(distance_distanceirrear_update_send());
  }
  if(is_distance_distanceusfront_send_requested)
  {
    is_distance_distanceusfront_send_requested = !(distance_distanceusfront_update_send());
  }
  if(is_distance_distanceusrear_send_requested)
  {
    is_distance_distanceusrear_send_requested = !(distance_distanceusrear_update_send());
  }
  if(is_batterylevel_batterylevel_send_requested)
  {
    is_batterylevel_batterylevel_send_requested = !(batterylevel_batterylevel_update_send());
  }
  if(is_generic_genericsensor1_send_requested)
  {
    is_generic_genericsensor1_send_requested = !(generic_genericsensor1_update_send());
  }
  if(is_generic_genericsensor2_send_requested)
  {
    is_generic_genericsensor2_send_requested = !(generic_genericsensor2_update_send());
  }
}

