/* 
* Copyright (c) 2013, Nordic Semiconductor ASA
* All rights reserved.
* 
* Redistribution and use in source and binary forms, with or without modification,
* are permitted provided that the following conditions are met:
* 
* - Redistributions of source code must retain the above copyright notice, this
*   list of conditions and the following disclaimer.
* 
* - Redistributions in binary form must reproduce the above copyright notice, this
*   list of conditions and the following disclaimer in the documentation and/or
*   other materials provided with the distribution.
* 
* - The name of Nordic Semiconductor ASA may not be used to endorse or promote
*   products derived from this software without specific prior written permission.
* 
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
* ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
* ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
* (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
* LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
* ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
* SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/**
* This file is autogenerated by nRFgo Studio 1.16.1.3119
*/

#include "services.h"
#include "lib_aci.h"

static bool is_gap_device_name_set_requested = false;
static bool is_sensors_sensors_send_requested = false;
static bool is_distance_distance_send_requested = false;
static bool is_actors_actors_send_requested = false;
static bool is_actors_actors_genericactor_set_requested = false;
static bool is_drive_speedandangle_send_requested = false;

static void *gap_device_name_set;
static uint8_t gap_device_name_set_size;
static void *sensors_sensors_tx;
static uint8_t sensors_sensors_tx_size;
static void *distance_distance_tx;
static uint8_t distance_distance_tx_size;
static void *actors_actors_tx;
static uint8_t actors_actors_tx_size;
static void *actors_actors_set_genericactor;
static uint8_t actors_actors_set_genericactor_size;
static void *drive_speedandangle_tx;
static uint8_t drive_speedandangle_tx_size;

static bool gap_device_name_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_GAP_DEVICE_NAME_SET, (void*)gap_device_name_set, gap_device_name_set_size));
}

void services_set_gap_device_name(void *src, int size)
{
  gap_device_name_set_size = size;
  gap_device_name_set = src;
  is_gap_device_name_set_requested = true;
  services_update_pipes();
}
static bool sensors_sensors_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_SENSORS_SENSORS_TX))
  {
    return(lib_aci_send_data(PIPE_SENSORS_SENSORS_TX, (void*)sensors_sensors_tx, sensors_sensors_tx_size));
  }
  return(false);
}

bool services_send_sensors_sensors(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_sensors_sensors_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_sensors_sensors_send_requested)
    {
      sensors_sensors_tx_size = size;
      sensors_sensors_tx = src;
      is_sensors_sensors_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    sensors_sensors_tx_size = size;
    sensors_sensors_tx = src;
    is_sensors_sensors_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool distance_distance_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_DISTANCE_DISTANCE_TX))
  {
    return(lib_aci_send_data(PIPE_DISTANCE_DISTANCE_TX, (void*)distance_distance_tx, distance_distance_tx_size));
  }
  return(false);
}

bool services_send_distance_distance(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_distance_distance_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_distance_distance_send_requested)
    {
      distance_distance_tx_size = size;
      distance_distance_tx = src;
      is_distance_distance_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    distance_distance_tx_size = size;
    distance_distance_tx = src;
    is_distance_distance_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool actors_actors_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_ACTORS_ACTORS_TX))
  {
    return(lib_aci_send_data(PIPE_ACTORS_ACTORS_TX, (void*)actors_actors_tx, actors_actors_tx_size));
  }
  return(false);
}

bool services_send_actors_actors(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_actors_actors_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_actors_actors_send_requested)
    {
      actors_actors_tx_size = size;
      actors_actors_tx = src;
      is_actors_actors_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    actors_actors_tx_size = size;
    actors_actors_tx = src;
    is_actors_actors_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool actors_actors_update_set_genericactor(void)
{
  return(lib_aci_set_local_data(PIPE_ACTORS_ACTORS_SET_GENERICACTOR, (void*)actors_actors_set_genericactor, actors_actors_set_genericactor_size));
}

void services_set_actors_actors_genericactor(void *src, int size)
{
  actors_actors_set_genericactor_size = size;
  actors_actors_set_genericactor = src;
  is_actors_actors_genericactor_set_requested = true;
  services_update_pipes();
}
static bool drive_speedandangle_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_DRIVE_SPEEDANDANGLE_TX))
  {
    return(lib_aci_send_data(PIPE_DRIVE_SPEEDANDANGLE_TX, (void*)drive_speedandangle_tx, drive_speedandangle_tx_size));
  }
  return(false);
}

bool services_send_drive_speedandangle(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_drive_speedandangle_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_drive_speedandangle_send_requested)
    {
      drive_speedandangle_tx_size = size;
      drive_speedandangle_tx = src;
      is_drive_speedandangle_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    drive_speedandangle_tx_size = size;
    drive_speedandangle_tx = src;
    is_drive_speedandangle_send_requested = true;
    services_update_pipes();
    return(true);
  }
}

void services_update_pipes(void)
{
  if(is_gap_device_name_set_requested)
  {
    is_gap_device_name_set_requested = !(gap_device_name_update_set());
  }
  if(is_sensors_sensors_send_requested)
  {
    is_sensors_sensors_send_requested = !(sensors_sensors_update_send());
  }
  if(is_distance_distance_send_requested)
  {
    is_distance_distance_send_requested = !(distance_distance_update_send());
  }
  if(is_actors_actors_send_requested)
  {
    is_actors_actors_send_requested = !(actors_actors_update_send());
  }
  if(is_actors_actors_genericactor_set_requested)
  {
    is_actors_actors_genericactor_set_requested = !(actors_actors_update_set_genericactor());
  }
  if(is_drive_speedandangle_send_requested)
  {
    is_drive_speedandangle_send_requested = !(drive_speedandangle_update_send());
  }
}

